name: Release community packages

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  schedule:
    - cron: '40 22 * * *'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release community packages
    permissions:
      contents: read
      id-token: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build packages
        run: |
          pnpm run --filter @workers-community/_repo-scripts build

      - name: Publish all packages
        env:
          NPM_CONFIG_PROVENANCE: true
        run: |
          pnpm -r publish --access public --no-git-checks --provenance
